import = [
    "~/.config/alacritty/themes/solarized_osaka.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[cursor]
style = "Beam"

[font.normal]
family = "Monospace"

[window]
title = "Alacritty"
dynamic_title = false
opacity = 0.95
padding =  { x = 15, y = 15 }
