import = [
    "~/.config/alacritty/themes/solarized_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[cursor]
style = "Beam"

[font.normal]
family = "JetBrains Mono"

[window]
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false
opacity = 0.9
padding =  { x = 15, y = 15 }
